config/routes.rb
Rails.application.routes.draw do
  get "/vehicle_configs", to: redirect("/research", status: 302)
  get '/vehicle_configs/:id', to: redirect('/research/%{id}', status: 302)
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  authenticate :user, lambda { |u| u.is_super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "vehicle_configs_admin/admin#index"
  get '/workbench' => 'workbench#index'
  get '/discord' => 'discord#index'
  get '/patreon' => 'patreon#index'
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap
  get '/lookup' => "vehicle_lookups_admin/admin#new"
  get "/u/:id" => "users_admin/admin#show"
  get '/garage' => "user_vehicles_admin/admin#index"
  get "/vehicles" => "vehicle_configs_admin/admin#index"
  get "/vehicles/make/:q" => "vehicle_configs_admin/admin#index", as: "vehicles_make"
  get "/vehicles/top" => "vehicle_configs_admin/admin#index", as: "vehicles_top", default: { order: "desc", sort: "cached_votes_score"}
  get "/vehicles/:id" => "vehicle_configs_admin/admin#show", as: "vehicles_show"

end

app/views/admin/vehicles/_capabilities_chart.html.erb
<% config_types = VehicleConfigType.all.order(:difficulty_level) %>
<% capability_matrix = @config.capability_matrix %>
<div class="capabilities">
  <div class="capability capability-head">
    <span class="key">Capability</span>
    <%=@config.config_type_ids%>
    <% config_types.each do |type| %>
    <%=@config.config_type_ids.include?(type.id)%>
    <% if @config.config_type_ids.include?(type.id) %>
    <span class="value type-<%=type.name.parameterize%>"><%=type.name%><span title="<%=type.description%>" data-container="body" data-toggle="tooltip" class="fa fa-info"></span></span>
    <% end %>
    <% end %>
  </div>
  <% @config.combined_capabilities.each do |capability| %>
    <% capability_key = capability.name.parameterize %>
  <div class="capability">
    <span class="key">
    <%=capability.name %>
    <span class="details">
      <%=capability.description%>
    </span>
    </span>
    <% config_types.each do |type| %>
      <% if @config.config_type_ids.include?(type.id) %>
        <% type_key = type.name.parameterize %>
        <% cap = capability_matrix[type_key.to_sym][capability_key.to_sym] %>
        <span class="value type-<%=type_key%><%if cap.present?%> active<% end %>">
          <% if cap.present? %>
            <%=cap[:value]%>
          <% end %>
        </span>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/admin/vehicles/_global_alert.html.erb
<div class="alert alert-danger">
  <strong style="margin-right:20px;font-size:25px;"><span class="fa fa-exclamation"></span></strong>
  <p style="font-size:12px;">
    <strong>THESE PAGES ARE IN HEAVY DEVELOPMENT AND SHOULD BE CONSIDERED A WORK-IN-PROGRESS.</strong><br />
    Much of this information is just wrong. As we get it stablized, we will remove this alert.<br />
    Please connect with us on <a href="https://slack.comma.ai/" target="_blank">Comma Slack</a> before making any decisions or doing any modifications.
  </p>
</div>

app/views/admin/vehicles/_profile_image.html.erb
<div class="profile-image">
  <%=image_tag(instance.image.service_url)%>
</div>

app/views/admin/vehicles/_profile_sidebar.html.erb
<div class="profile-sidebar">
  <%=yield%>
</div>

app/views/admin/vehicles/index.html.erb
<h1>Vehicles</h1>
<%=render "global_alert"%>
<div class="vehicles">
<% @makes.each do |make| %>
  <div class="make-box">
    <div class="make-box-header"><%=link_to(make.name, vehicles_admin_make_path(make_slug: make.slug))%></div>
    <ul class="make-box-models">
      <% make.vehicle_models_with_configs.each do |model| %>
        <li>
          <%=link_to(model.name, vehicles_admin_model_path(make_slug: make.slug, model_slug: model.slug))%>
        </li>
      <% end%>
    </ul>
  </div>
<% end %>
</div>

app/views/admin/vehicles/lookup.html.erb
<div class="lookup-form">
<div class="main-content-area">
<div class="main-content-container">
<div class="main-content">
<%= form_for @vehicle_config, url: admin.path(:create), method: :post do |f| %>
  <div class="row">
    <div class="col-sm-3 col-class-year-range">
      <div class="row">
        <div class="col-sm-6 col-class-year-start">
          <div class="form-group">
            <label class="control-label" for="vehicle_config_year">Year</label>
            <%= f.select :year, 2010..(Time.zone.now.year + 2) %>
          </div>
        </div>
        <div class="col-sm-6 col-class-year-end">
          <div class="form-group">
            <label class="control-label" for="vehicle_config_year_end">Year</label>
            <%= f.select :year_end, 2010..(Time.zone.now.year + 2) %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <label class="control-label" for="vehicle_config_make">Make</label>
        <%=f.collection_select :vehicle_make_id, VehicleMake.order(:name), :id, :name, include_blank: true%>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <label class="control-label" for="vehicle_config_make">Model</label>
        <%=f.collection_select :vehicle_model_id, VehicleModel.order(:name), :id, :name, include_blank: true%>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>
</div>
</div>

app/views/admin/vehicles/make.html.erb
<% title = @make.name %>
<% content_for(:title, title) %>
<% breadcrumb(title) %>

<h1><%=title%></h1>
<%=render "global_alert"%>
<p>
Openpilot has some compatibility with <strong><%=@make.name%></strong> model(s) so browse the model pages below for additional specifics. 
</p>
<p>
The goal is to always support as many vehicles as possible.<br />If you have development experience, or even if you don't - we would love to help you port more cars.
</p>

<% if !@make.slack_channel.blank? %>
<p>
To chat about <%=@make.name%>'s with the community, checkout the <a href="slack://channel?team=comma&id=<%=@make.slack_channel%>">#<%=@make.slack_channel%></a> channel in the <a href="https://slack.comma.ai" target="_blank">Comma Slack</a>.
</p>
<% end %>

<h2>Research and Support</h2>

<p>We're always researching new and exciting vehicles to support.  Some of them we've cracked, and some of them are in progress.</p>
<p>Below is a list of models we have began supporting and/or researching.</p>

<ul>
<% @make.vehicle_models_with_configs.each do |model| %>
  <li><%=link_to(model.name, vehicles_admin_model_path(make_slug: @make.slug, model_slug: model.slug))%></li>
<% end %>
</ul>

<h2>How to add support for a vehicle</h2>
<p>
If you own an unsupported vehicle but are interested in discussing porting it to openpilot, join us in the NEW openpilot community chat support system and the always popular Comma.ai Slack if you prefer it.
</p>
<p>
There will also be some great info on porting models in Development Guides.
</p>

app/views/admin/vehicles/model.html.erb
<% title = "#{@make.name} #{@model.name}" %>
<% content_for(:title, title) %>
<% breadcrumb(title) %>

<h1><%=title%></h1>
<%=render "global_alert"%>

<p>
Openpilot has some compatibility with the <strong><%=@model.name %></strong> and this page serves as a general overview of the model.<br />
To get more specific details on compatibility of a particular trim ensure you check the trim links below to learn more.
</p>

<p>The goal is to always support as many vehicles as possible.</p>

<% if !@make.slack_channel.blank? %>
<p>
To chat about the <%=title%> with the community, checkout the <a href="slack://channel?team=comma&id=<%=@make.slack_channel%>">#<%=@make.slack_channel%></a> channel in the <a href="https://slack.comma.ai" target="_blank">Comma Slack</a>.
</p>
<% end %>

<h2>Research and Support</h2>

<p>We're always researching new and exciting vehicles to support.<br />Some of them are ported, and some of them will take work.</p>
<p>Below is a list of models we have begun supporting and/or researching.</p>

<ul>
  <% @model.vehicle_configs.where(parent_id: nil).each do |config| %>
  <li>
    <%=link_to config.name, vehicles_admin_show_path(config.slug.present? ? config.slug : config.id)%>
  </li>
  <% end %>
</ul>

app/views/admin/vehicles/show.html.erb
<% content_for(:title, @title) %>
<% breadcrumb(@title) %>


        <%= render "trestle/shared/fundraiser" %>
<div class="profile">
  <div class="profile-content">
    <h1><%=@title%></h1>
    <%=render "global_alert" %>

    <% if @config.present? && @config.is_upstreamed? %>
    <p>
      Openpilot has some compatibility with the <strong><%=@model.name %></strong> and this page serves as a general overview of the model.<br />
      To get more specific details on compatibility of a particular trim ensure you check the trim links below to learn more.
    </p>
    <% else %>
    <p>
      Openpilot does not have plug-and-play support yet for the <strong><%=@model.name %></strong> but all is not lost.<br />
      If your vehicle has the basic hardware requirements that Openpilot needs, you may still be in luck!<br />
      Read on to check which of the <%=@model.name.pluralize%> have what we need.
    </p>
    <% end%>

    <p>The goal is to always support as many vehicles as possible.</p>

  
    <div class="alert alert-warning">
    <span class="fa fa-comment" style="font-size:25px; margin-right:20px;"></span> To chat about the <%=@make.name%> <%=@model.name%> with the community, <% if !@make.slack_channel.blank? %><a href="slack://channel?team=comma&id=<%=@make.slack_channel%>">checkout the #<%=@make.slack_channel%></a> channel in the<% else %> join the conversation on the <% end %> <a href="https://comma.slack.com/" target="_blank">Comma Slack</a>.
    </div>

    <h2>Research and Support</h2>

    <p>The first thing we need to know is if the vehicle has Adaptive Cruise Control (ACC) and Lane Keeping Assist (LKA).
    <% if @make.vehicle_make_packages.present? %>
      <br />On <%=@make.name%> vehicles, this is called the <%=@make.vehicle_make_packages.map(&:name).join(',')%> package.</p>
    <% end %>
    <p>Although most model trims have similar factory hardware, some may differ slightly so ensure you check the trim pages for specifics.</p>
    <%# <p>We've found the following trims for this configuration.</p> %>

    <h3>Identify your exact trim</h3>
    <h4>Standard Trims</h4>

    <p>The following trims come standard with the features required for Openpilot to work effectively.</p>
    <div class="alert alert-info"><strong style="margin-right:25px;">NOTE</strong> Although they come with these features, it is not guaranteed that Openpilot is 100% compatible. 
    If you discover any issues, work with a community member to get your vehicle ported to reach its full potential.</div>

    <ul>
      <% @trims.select{|ts| ts.driver_assist_inclusion == "standard"}.each do |trim| %>
      <li>
        <%=link_to vehicles_admin_show_year_trim_path(make_slug: @make.slug, model_slug: @model.slug, year: @year, trim_style_id: trim.id) do %>
          <%=trim.year%> <%=trim.name%>
        <% end %>
      </li>
      <% end %>
    </ul>

    <%if @config.present? && @config.vehicle_make_package.present? %>
      <h4>Trims w/ <%=@config.vehicle_make_package.name %> Option</h4>

      <p>The following trims do not come standard with the features required for Openpilot to work effectively.</p>
      <p>Review the features that come with these models thoroughly to ensure your vehicle has the right hardware.</p>

      <ul>
        <% @trims.select{|ts| ts.driver_assist_inclusion == "option" }.each do |trim| %>
        <li>
          <%=link_to vehicles_admin_show_year_trim_path(make_slug: @make.slug, model_slug: @model.slug, year: @year, trim_style_id: trim.id) do %>
            <%=trim.year%> <%=trim.name%>
          <% end %>
        </li>
        <% end %>
      </ul>
    <% end %>

    <h4>Not Supported</h4>

      <p>Unfortunately the following <%=@make.name%> <%@model.name%> trim(s) are not supported.</p>
      <p>They simply lack the hardware necessary for Openpilot to work without significant modification.</p>

      <ul>
        <% @trims.select{|ts| ts.driver_assist_inclusion.blank? }.each do |trim| %>
        <li>
          <%=trim.year%> <%=trim.name%>
        </li>
        <% end %>
      </ul>
  </div>

  <div class="profile-sidebar">
    <div class="profile-sidebar-inner">
      <% if @image.present? && @image.attached? %>
        <div class="profile-image">
          <%=image_tag(@image.service_url)%>
        </div>
      <% end %>

      <div class="specs">
        <div class="spec">
          <span class="key">
            Name
          </span>
          <span class="value">
            <%=@model.name%>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/vehicles/show_trim.html.erb
<% title = "#{@trim.name_for_docs}" %>
<% content_for(:title, title) %>
<% breadcrumb(title) %>
<div class="profile">
  <div class="profile-content">
    <h1><%=@trim.name_for_docs%></h1>
    <%=render "global_alert"%>
    <p>
    Openpilot has some compatibility with the <strong><%=@model.name %></strong> and this page serves as a general overview of the model.
    This page has the most specific information about a particular trim and what is required to get Openpilot working.</p>

    <p>The goal is to always support as many vehicles as possible.</p>

    <div class="alert alert-warning">
      <span class="fa fa-comment" style="font-size:25px; margin-right:20px;"></span> To chat about the <%=@make.name%> <%=@model.name%> with the community, <% if !@make.slack_channel.blank? %><a href="slack://channel?team=comma&id=<%=@make.slack_channel%>">checkout the #<%=@make.slack_channel%></a> channel in the<% else %> join the conversation on the <% end %> <a href="https://comma.slack.com/" target="_blank">Comma Slack</a>.
    </div>

    <h2>Configurations</h2>

    <p>Many trims have configurations available that support Openpilot.</p>
    <p>We're trying to make it easy to compare each configuration so you can see what capabilities you gain from using Openpilot and which capabilities you unfortunately sometimes lose with Openpilot.</p>
    <p>These configurations are one of 4 setups: Factory, Standard, Basic and Advanced.</p>
    
    <% if @config.present? %>
      <%=render "capabilities_chart" %>
    <% else %>
    <div class="alert alert-warning">
      <div>
        <h3 style="margin:0;">You can help us port it!</h3>
        <p>At this time, we haven't gathered enough information or began porting this <%=@make.name%> model.  But perhaps that will change very soon!</p>
        <p>If you're a developer, you could easily begin the journey of your first Openpilot port of your car. Doing a port once, makes it work for everyone with this same vehicle and helps the community thrive.</p>
      </div>
    </div>
    <% end %>
  </div>

  <div class="profile-sidebar">
    <div class="profile-sidebar-inner">
      <% if @trim.image.present? && @trim.image.attached? %>
        <div class="profile-image">
          <%=image_tag(@trim.image.service_url)%>
        </div>
      <% end %>

      <div class="specs">
        <div class="spec">
          <span class="key">
            Name
          </span>
          <span class="value">
            <%=@trim.name%>
          </span>
        </div>

        <div class="spec">
          <span class="key">
            Inventory Price
          </span>
          <span class="value">
            <%=@trim.inventory_prices%>
          </span>
        </div>
        <div class="spec">
          <span class="key">
            MPG
          </span>
          <span class="value">
            <%=@trim.mpg%>
          </span>
        </div>
        <div class="spec">
          <span class="key">
            Engine
          </span>
          <span class="value">
            <%=@trim.engine%>
          </span>
        </div>
        <div class="spec">
          <span class="key">
            Transmission
          </span>
          <span class="value">
            <%=@trim.trans%>
          </span>
        </div>
        <div class="spec">
          <span class="key">
            Drive
          </span>
          <span class="value">
            <%=@trim.drive%>
          </span>
        </div>
        <div class="spec">
          <span class="key">
            Colors
          </span>
          <span class="value">
            <%=@trim.colors%>
          </span>
        </div>
        <div class="spec">
          <span class="key">
            Seats
          </span>
          <span class="value">
            <%=@trim.seats%>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>